'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:2.0.50727.4206
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Josco.JSOA.web

    Partial Public Class estate_es_yjjt

        '''<summary>
        '''frmestate_es_yjjt 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents frmestate_es_yjjt As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''panelMain 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents panelMain As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lnkBlank 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents lnkBlank As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''txtYJSearch_RYDM 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtYJSearch_RYDM As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtYJSearch_RYMC 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtYJSearch_RYMC As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtYJSearch_JYNYMin 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtYJSearch_JYNYMin As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtYJSearch_JYNYMax 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtYJSearch_JYNYMax As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtYJSearch_JANYMin 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtYJSearch_JANYMin As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtYJSearch_JANYMax 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtYJSearch_JANYMax As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnYJSearch 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents btnYJSearch As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnYJSearch_Full 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents btnYJSearch_Full As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''grdYJ 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents grdYJ As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''htxtYJFixed 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtYJFixed As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''lnkCZYJDeSelectAll 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents lnkCZYJDeSelectAll As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lnkCZYJSelectAll 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents lnkCZYJSelectAll As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lnkCZYJMoveFirst 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents lnkCZYJMoveFirst As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lnkCZYJMovePrev 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents lnkCZYJMovePrev As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lnkCZYJMoveNext 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents lnkCZYJMoveNext As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lnkCZYJMoveLast 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents lnkCZYJMoveLast As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lnkCZYJGotoPage 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents lnkCZYJGotoPage As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''txtYJPageIndex 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtYJPageIndex As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lnkCZYJSetPageSize 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents lnkCZYJSetPageSize As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''txtYJPageSize 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtYJPageSize As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblYJGridLocInfo 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents lblYJGridLocInfo As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''btnPrint 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents btnPrint As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnClose 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents btnClose As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''panelError 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents panelError As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblMessage 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''btnGoBack 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents btnGoBack As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''htxtSessionIdQueryYJ 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtSessionIdQueryYJ As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtYJQuery 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtYJQuery As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtYJRows 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtYJRows As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtYJSort 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtYJSort As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtYJSortColumnIndex 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtYJSortColumnIndex As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtYJSortType 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtYJSortType As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtDivLeftYJ 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtDivLeftYJ As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtDivTopYJ 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtDivTopYJ As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtDivLeftBody 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtDivLeftBody As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtDivTopBody 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtDivTopBody As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''popMessageObject 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents popMessageObject As Global.Josco.Web.PopMessage
    End Class
End Namespace
