'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:2.0.50727.4206
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Josco.JSOA.web

    Partial Public Class estate_es_hetongzl_qry

        '''<summary>
        '''frmestate_es_hetongzl_qry 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents frmestate_es_hetongzl_qry As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''panelMain 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents panelMain As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lnkBlank 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents lnkBlank As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''txtQRSH 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtQRSH As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtHTBH 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtHTBH As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtKYBH 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtKYBH As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtDGRQMin 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtDGRQMin As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtDGRQMax 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtDGRQMax As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtHTRQMin 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtHTRQMin As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtHTRQMax 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtHTRQMax As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtTJRQMin 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtTJRQMin As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtTJRQMax 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtTJRQMax As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtJARQMin 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtJARQMin As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtJARQMax 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtJARQMax As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cblHTJA 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents cblHTJA As Global.System.Web.UI.WebControls.CheckBoxList

        '''<summary>
        '''cblHTSH 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents cblHTSH As Global.System.Web.UI.WebControls.CheckBoxList

        '''<summary>
        '''cblHTJC 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents cblHTJC As Global.System.Web.UI.WebControls.CheckBoxList

        '''<summary>
        '''cblHTHZ 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents cblHTHZ As Global.System.Web.UI.WebControls.CheckBoxList

        '''<summary>
        '''txtCCDZ 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtCCDZ As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtCCFMin 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtCCFMin As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtCCFMax 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtCCFMax As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtJYYZJMin 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtJYYZJMin As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtJYYZJMax 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtJYYZJMax As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtJFDLFMin 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtJFDLFMin As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtJFDLFMax 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtJFDLFMax As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtYFDLFMin 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtYFDLFMin As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtYFDLFMax 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtYFDLFMax As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtJYZZJMin 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtJYZZJMin As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtJYZZJMax 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtJYZZJMax As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtSSYJMin 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtSSYJMin As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtSSYJMax 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtSSYJMax As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtHZYJMin 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtHZYJMin As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtHZYJMax 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtHZYJMax As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtDLFZKMin 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtDLFZKMin As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtDLFZKMax 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtDLFZKMax As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtAJFHMin 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtAJFHMin As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtAJFHMax 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtAJFHMax As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtJCRQMin 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtJCRQMin As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtJCRQMax 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtJCRQMax As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtHZJEMin 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtHZJEMin As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtHZJEMax 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtHZJEMax As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtHZRQMin 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtHZRQMin As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtHZRQMax 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtHZRQMax As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtFYBH 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtFYBH As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtFCZH 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtFCZH As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtFWDZ 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtFWDZ As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtFCZDZ 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtFCZDZ As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtLP 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtLP As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtLD 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtLD As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtDY 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtDY As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ddlSZQY 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents ddlSZQY As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtSZQYList 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtSZQYList As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtMJMin 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtMJMin As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtMJMax 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtMJMax As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtJCSJMin 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtJCSJMin As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtJCSJMax 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtJCSJMax As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtLLMin 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtLLMin As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtLLMax 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtLLMax As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cblKJLX 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents cblKJLX As Global.System.Web.UI.WebControls.CheckBoxList

        '''<summary>
        '''cblFWXZ 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents cblFWXZ As Global.System.Web.UI.WebControls.CheckBoxList

        '''<summary>
        '''txtLGMin 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtLGMin As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtLGMax 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtLGMax As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtDTSLMin 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtDTSLMin As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtDTSLMax 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtDTSLMax As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtLCHSMin 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtLCHSMin As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtLCHSMax 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtLCHSMax As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtLPQSMin 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtLPQSMin As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtLPQSMax 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtLPQSMax As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cblCX 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents cblCX As Global.System.Web.UI.WebControls.CheckBoxList

        '''<summary>
        '''cblWYSX 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents cblWYSX As Global.System.Web.UI.WebControls.CheckBoxList

        '''<summary>
        '''cblZXDC 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents cblZXDC As Global.System.Web.UI.WebControls.CheckBoxList

        '''<summary>
        '''cblZXNX 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents cblZXNX As Global.System.Web.UI.WebControls.CheckBoxList

        '''<summary>
        '''cblZYYX 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents cblZYYX As Global.System.Web.UI.WebControls.CheckBoxList

        '''<summary>
        '''cblJJSB 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents cblJJSB As Global.System.Web.UI.WebControls.CheckBoxList

        '''<summary>
        '''cblLYJT 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents cblLYJT As Global.System.Web.UI.WebControls.CheckBoxList

        '''<summary>
        '''cblFWJG 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents cblFWJG As Global.System.Web.UI.WebControls.CheckBoxList

        '''<summary>
        '''cblJGLX 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents cblJGLX As Global.System.Web.UI.WebControls.CheckBoxList

        '''<summary>
        '''txtJGFSMin 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtJGFSMin As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtJGFSMax 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtJGFSMax As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtLCMin 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtLCMin As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtLCMax 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtLCMax As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtWSSLMin 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtWSSLMin As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtWSSLMax 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtWSSLMax As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtYTSLMin 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtYTSLMin As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtYTSLMax 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtYTSLMax As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtYZJEMin 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtYZJEMin As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtYZJEMax 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtYZJEMax As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ddlJG 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents ddlJG As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtJGList 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtJGList As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtZLKSMin 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtZLKSMin As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtZLKSMax 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtZLKSMax As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtZLJSMin 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtZLJSMin As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtZLJSMax 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtZLJSMax As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cblSDMQ 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents cblSDMQ As Global.System.Web.UI.WebControls.CheckBoxList

        '''<summary>
        '''cblDHF 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents cblDHF As Global.System.Web.UI.WebControls.CheckBoxList

        '''<summary>
        '''cblGLF 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents cblGLF As Global.System.Web.UI.WebControls.CheckBoxList

        '''<summary>
        '''cblZLFP 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents cblZLFP As Global.System.Web.UI.WebControls.CheckBoxList

        '''<summary>
        '''txtJFMC 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtJFMC As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtJFDLR 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtJFDLR As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cblJFZJLB 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents cblJFZJLB As Global.System.Web.UI.WebControls.CheckBoxList

        '''<summary>
        '''txtJFZZHM 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtJFZZHM As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cblSYWY 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents cblSYWY As Global.System.Web.UI.WebControls.CheckBoxList

        '''<summary>
        '''txtJFLXDH 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtJFLXDH As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cblYZQC 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents cblYZQC As Global.System.Web.UI.WebControls.CheckBoxList

        '''<summary>
        '''txtYZQN 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtYZQN As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cblYZLY 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents cblYZLY As Global.System.Web.UI.WebControls.CheckBoxList

        '''<summary>
        '''txtYYQT 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtYYQT As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtJFLXDZ 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtJFLXDZ As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtYZDY 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtYZDY As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtYFMC 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtYFMC As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtYFDLR 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtYFDLR As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cblYFZJLB 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents cblYFZJLB As Global.System.Web.UI.WebControls.CheckBoxList

        '''<summary>
        '''txtYFZZHM 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtYFZZHM As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtYFLXDH 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtYFLXDH As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cblMJQC 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents cblMJQC As Global.System.Web.UI.WebControls.CheckBoxList

        '''<summary>
        '''txtMJQN 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtMJQN As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cblKHLY 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents cblKHLY As Global.System.Web.UI.WebControls.CheckBoxList

        '''<summary>
        '''txtKYQT 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtKYQT As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtYFLXDZ 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtYFLXDZ As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtKHDY 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtKHDY As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtJYZMJMin 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtJYZMJMin As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtJYZMJMax 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtJYZMJMax As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtHTFWDZ 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtHTFWDZ As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtZLBZJMin 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtZLBZJMin As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtZLBZJMax 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtZLBZJMax As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtZQYSMin 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtZQYSMin As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtZQYSMax 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtZQYSMax As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ddlFKFS 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents ddlFKFS As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''txtFKFSList 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtFKFSList As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cblFZFSYD 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents cblFZFSYD As Global.System.Web.UI.WebControls.CheckBoxList

        '''<summary>
        '''txtJZRMin 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtJZRMin As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtJZRMax 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtJZRMax As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtZNJBLMin 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtZNJBLMin As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtZNJBLMax 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtZNJBLMax As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtNDZBLMin 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtNDZBLMin As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtNDZBLMax 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtNDZBLMax As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtJLRQMin 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtJLRQMin As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtJLRQMax 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtJLRQMax As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtJLZKSM 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtJLZKSM As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cblSFZFYD 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents cblSFZFYD As Global.System.Web.UI.WebControls.CheckBoxList

        '''<summary>
        '''cblZJTGYD 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents cblZJTGYD As Global.System.Web.UI.WebControls.CheckBoxList

        '''<summary>
        '''txtBZXX 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtBZXX As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtYWRYMC 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtYWRYMC As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtYWBMMC 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtYWBMMC As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtTDBHMin 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtTDBHMin As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtTDBHMax 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtTDBHMax As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cblYWRYZJ 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents cblYWRYZJ As Global.System.Web.UI.WebControls.CheckBoxList

        '''<summary>
        '''txtFPBLMin 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtFPBLMin As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtFPBLMax 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtFPBLMax As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''btnOK 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents btnOK As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnReset 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents btnReset As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnClose 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents btnClose As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''panelError 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents panelError As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblMessage 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''btnGoBack 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents btnGoBack As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''htxtDivLeftMain 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtDivLeftMain As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtDivTopMain 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtDivTopMain As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtDivLeftBody 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtDivLeftBody As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtDivTopBody 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtDivTopBody As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''popMessageObject 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents popMessageObject As Global.Josco.Web.PopMessage
    End Class
End Namespace
