'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:2.0.50727.3615
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Josco.JSOA.web

    Partial Public Class flow_cuiban

        '''<summary>
        '''frmFLOW_CUIBAN 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents frmFLOW_CUIBAN As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''panelMain 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents panelMain As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lnkBlank 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents lnkBlank As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lblKCBXXGridLocInfo 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents lblKCBXXGridLocInfo As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''grdKCBXX 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents grdKCBXX As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''htxtKCBXXFixed 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtKCBXXFixed As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''lblYCBXXGridLocInfo 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents lblYCBXXGridLocInfo As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''grdYCBXX 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents grdYCBXX As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''htxtYCBXXFixed 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtYCBXXFixed As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''btnOK 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents btnOK As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnCancel 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''panelError 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents panelError As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblMessage 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''htxtSessionIdKCBXX 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtSessionIdKCBXX As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtKCBXXQuery 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtKCBXXQuery As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtKCBXXRows 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtKCBXXRows As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtKCBXXSort 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtKCBXXSort As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtKCBXXSortColumnIndex 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtKCBXXSortColumnIndex As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtKCBXXSortType 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtKCBXXSortType As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtYCBXXQuery 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtYCBXXQuery As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtYCBXXRows 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtYCBXXRows As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtYCBXXSort 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtYCBXXSort As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtYCBXXSortColumnIndex 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtYCBXXSortColumnIndex As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtYCBXXSortType 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtYCBXXSortType As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtDivLeftKCBXX 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtDivLeftKCBXX As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtDivTopKCBXX 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtDivTopKCBXX As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtDivLeftYCBXX 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtDivLeftYCBXX As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtDivTopYCBXX 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtDivTopYCBXX As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtDivLeftBody 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtDivLeftBody As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtDivTopBody 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtDivTopBody As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''popMessageObject 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents popMessageObject As Global.Josco.Web.PopMessage
    End Class
End Namespace
