'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行库版本:2.0.50727.1882
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Josco.JSOA.web

    Partial Public Class estate_rs_shixisheng

        '''<summary>
        '''frmestate_rs_luyong_main 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents frmestate_rs_luyong_main As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''panelMain 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents panelMain As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lnkBlank 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents lnkBlank As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lnkMenu 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents lnkMenu As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''htxtSelectMenuID 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtSelectMenuID As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtMenuParam00 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtMenuParam00 As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''mnuMain 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuMain As Global.ComponentArt.Web.UI.Menu

        '''<summary>
        '''mnuNew 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuNew As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuOpen 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuOpen As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuDelete 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuDelete As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuXXCY 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuXXCY As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuXXCY_CKLZ 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuXXCY_CKLZ As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuPrint 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuPrint As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuPrint_DYQD 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuPrint_DYQD As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuUnlock 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuUnlock As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuRefresh 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuRefresh As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''mnuClose 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents mnuClose As Global.ComponentArt.Web.UI.MenuItem

        '''<summary>
        '''txtRSLYGLSearch_WJBT 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtRSLYGLSearch_WJBT As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtRSLYGLSearch_JBRQMin 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtRSLYGLSearch_JBRQMin As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtRSLYGLSearch_JBRQMax 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtRSLYGLSearch_JBRQMax As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtRSLYGLSearch_QFRQMin 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtRSLYGLSearch_QFRQMin As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtRSLYGLSearch_QFRQMax 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtRSLYGLSearch_QFRQMax As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ddlRSLYGLSearch_BLZT 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents ddlRSLYGLSearch_BLZT As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''btnRSLYGLSearch 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents btnRSLYGLSearch As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''grdRSLYGL 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents grdRSLYGL As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''htxtRSLYGLFixed 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtRSLYGLFixed As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''lnkCZRSLYGLDeSelectAll 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents lnkCZRSLYGLDeSelectAll As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lnkCZRSLYGLSelectAll 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents lnkCZRSLYGLSelectAll As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lnkCZRSLYGLMoveFirst 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents lnkCZRSLYGLMoveFirst As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lnkCZRSLYGLMovePrev 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents lnkCZRSLYGLMovePrev As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lnkCZRSLYGLMoveNext 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents lnkCZRSLYGLMoveNext As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lnkCZRSLYGLMoveLast 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents lnkCZRSLYGLMoveLast As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lnkCZRSLYGLGotoPage 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents lnkCZRSLYGLGotoPage As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''txtRSLYGLPageIndex 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtRSLYGLPageIndex As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lnkCZRSLYGLSetPageSize 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents lnkCZRSLYGLSetPageSize As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''txtRSLYGLPageSize 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents txtRSLYGLPageSize As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblRSLYGLGridLocInfo 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents lblRSLYGLGridLocInfo As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''panelError 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents panelError As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblMessage 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''btnGoBack 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents btnGoBack As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''htxtSessionIdQuery 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtSessionIdQuery As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtRSLYGLQuery 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtRSLYGLQuery As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtRSLYGLRows 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtRSLYGLRows As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtRSLYGLSort 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtRSLYGLSort As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtRSLYGLSortColumnIndex 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtRSLYGLSortColumnIndex As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtRSLYGLSortType 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtRSLYGLSortType As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtDivLeftRSLYGL 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtDivLeftRSLYGL As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtDivTopRSLYGL 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtDivTopRSLYGL As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtDivLeftBody 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtDivLeftBody As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''htxtDivTopBody 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents htxtDivTopBody As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''popMessageObject 控件。
        '''</summary>
        '''<remarks>
        '''自动生成的字段。
        '''若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        '''</remarks>
        Protected WithEvents popMessageObject As Global.Josco.Web.PopMessage
    End Class
End Namespace
